<?php echo $this->partial('header.phtml', array('title'=>$this->title)); ?>
<div class="conter c-con">
	<div class="subnav">联系我们</div>
	<div class="a-content">
		<h3>商务合作</h3>
		<p><b>联系人</b>：马经理</p>
		<p><b>电　话</b>：（86）010-87361392</p>
		<p><b>Email</b>：mahongfeng@paimaihui.net</p>
		<hr>
		<h3>售后服务</h3>
		<p><b>联系人</b>：刘经理</p>
		<p><b>电　话</b>：（86）010-87361392</p>
		<p><b>Email</b>：liuzhen729@gmail.com</p>
	</div>
</div>
<?php echo $this->partial('footer.phtml'); ?>