<?php echo $this->partial('header.phtml', array('title'=>$this->title)); ?>

            <div id="counting">共<?php echo number_format($this->total) ?>条结果</div>

            <div id="listing">
            <?php
            	for ($i=0;$i<4;$i++) {
            ?>
                <div class="column">
                	<?php
                	for ($j=0; ($j<8 && $i+$j<count($this->antiques)); $j++) {
                		if ($this->antiques[$i+$j]) {
                			$antique = $this->antiques[$i+$j];
                	?>
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="<?php echo $this->url(array('action'=>'show', 'id'=>$antique['id']), '', true) ?>"><img src="http://www.chengxuan.com<?php echo $antique['thumbnail'] ?>" /></a>
                            <p>
                                <a href="<?php echo $this->url(array('action'=>'show', 'id'=>$antique['id']), '', true) ?>"><?php echo $antique['name'] ?></a>
                                <?php echo $this->activityInfo[$antique['activity_id']]['name'] ?> LOT <?php echo $antique['lot'] ?><br /><br />

                                <?php if ($antique['size']) { ?>尺寸: <?php echo $antique['size'] ?><br /><?php } ?>
                                <?php if ($antique['period']) { ?>年代: <?php echo $antique['period'] ?><br /><br /><?php } ?>

                                <?php if ($antique['appraisal_price']) { ?>估价: <?php echo $antique['appraisal_price'] ?><br /><?php } ?>
                                <?php if ($antique['deal_price']) { ?>成交价: <?php echo $antique['deal_price'] ?><?php } ?>
                            </p>
                        </div>
                    </div>
                    <?php }
                	
                	}?>
                </div>
            <?php }// end for i<4?>
            </div>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', //Elastic/Jumping/All
                                    'pagination.phtml'); ?>


<?php echo $this->partial('footer.phtml'); ?>