<?php echo $this->partial('header.phtml', array('title'=>$this->title)); ?>

            <div id="breadcrumbs">
                <a href="/">首页</a> &gt;
                <a href="#">北京诚轩</a> &gt;
                <a href="#">2012年春季拍卖会</a> &gt;
                <a href="#">瓷器工艺品</a> &gt;
                清中期 青花花卉纹壮罐
            </div>

            <div id="antique">
                <div class="picture">
                    <div class="content"><span></span>
                        <img src="http://www.chengxuan.com/images/<?php echo $this->antique['activity']['slug'] ?>/preview-<?php echo $this->antique['lot']?>.jpg" />
                    </div>
                </div>
                <div class="detail">
                    <h2><?php echo $this->antique['name'] ?></h2>
                    <div>
                        <p>嘉德 <?php echo $this->antique['activity']['name'] ?> LOT <?php echo $this->antique['lot'] ?></p>

                        <p>
                            尺寸: <?php echo $this->antique['size'] ?><br />
                            年代: <?php echo $this->antique['period'] ?>
                        </p>

                        <p class="last">
                            估价(人民币): <?php echo $this->antique['appraisal_price'] ?><br />
                            成交价(人民币): <?php echo number_format($this->antique['deal_price']) ?>
                        </p>
                    </div>
                    <h2>Qing Dynasty Blue and White Flower Cans</h2>
                    <div>
                        <p>LOT 4009 Spring Auction, 2012 of Guardian</p>

                        <p>
                            Size: Height 27.4CM, Weight 1600g<br />
                            Dynasty: Qing Dynasty, 1644-1911
                        </p>

                        <p class="last">
                            Estimate(RMB): <?php echo $this->antique['appraisal_price'] ?><br />
                            Price(RMB): <?php echo number_format($this->antique['deal_price']) ?>
                        </p>
                    </div>
                </div>
            </div>

            <div id="additional">
                <div id="relationship">
                    <h3>相关拍品</h3>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_01.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_02.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_03.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_04.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_07.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_08.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                </div>
                <div id="recommendation">
                    <h3>精彩推荐</h3>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_06.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_05.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_01.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_07.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_04.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                    <div class="column">
                        <div class="mini">
                            <div class="content"><span></span>
                                <a href="/page.html"><img src="/images/mini_02.jpg" /></a>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
<?php echo $this->partial('footer.phtml'); ?>