<?php echo $this->partial('header.phtml', array('title'=>$this->title)); ?>
<?php $company = $this->company;
$activity = $this->activity;
?>
<div class="conter c-con">
	<div class="subnav">当前位置：<a href="##">首页</a>&gt;<span>拍卖公司</span></div>
	<div class="s-title"><strong><?php echo $company['name']; ?></strong></div>
	<?php foreach ($activity as $act): ?>
	<div class="c-title">
		<strong><?php echo $act['name']?>（共<?php 
		echo $act['antique_count']?>件）</strong><em>成交额:<b><?php 
		echo number_format($act['amount']) ?></b></em><em>成交率：<b><?php 
		echo number_format($act['deal_rate'], 2, '.', '')?>%</b></em>
	</div>
	<ul>
		<?php foreach ($act['sub_activity'] as $sub): ?>
		<li class="clearfix">
			<img src="/images/pic-1.gif"/>
			<p>
				<a href="/sub-activity/show/id/<?php echo $sub['id'] ?>"><em><?php echo $sub['name']?></em>（<?php echo $sub['antique_count']?>件）</a><br />
				<?php echo $sub['event_date']?>
			</p>
		</li>
		<?php endforeach;?>
	</ul>
	<?php endforeach;?>	
	
	<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', //Elastic/Jumping/All
                                    'pagination.phtml'); ?>
                                    
</div>

<?php echo $this->partial('footer.phtml'); ?>