<?php echo $this->partial('header.phtml'); ?>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', //Elastic Jumping All
                                    'pagination.phtml'); ?>
            <div id="counting">共3,880,999条结果</div>

            <div id="listing">
                <div class="column">
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_01.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_02.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_03.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_04.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_05.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_06.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                </div>
                <div class="column">
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_07.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                    <div class="item">
                        <div class="content"><span></span>
                            <a href="/page.html"><img src="/images/thumb_08.jpg" /></a>
                            <p>
                                <a href="/page.html">清光绪 绿地黄彩云鹤纹苹果尊</a>
                                嘉德 2012年春拍 LOT 4009<br /><br />

                                尺寸: 高15厘米，直径8厘米<br />
                                年代: 清光绪<br /><br />

                                估价: 1,300,000 - 2,000,000<br />
                                成交价: 3,000,000
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div id="pagination">
                <a href="#">上一页</a>
                <a href="#">1</a>
                <span class="selected">2</span>
                <a href="#">3</a>
                <a href="#">4</a>
                <span class="etc">...</span>
                <a href="#">8</a>
                <a href="#">9</a>
                <a href="#">下一页</a>
            </div>


<?php echo $this->partial('footer.phtml'); ?>