<?php echo $this->partial('header.phtml', array('title'=>$this->title)); ?>
<?php $sub = $this->subActivity;
$antiques = $this->antiques;
?>

<div class="conter s-con">
	<div class="subnav">当前位置：<a href="/">首页</a>
		&gt; <a href="<?php echo $this->url(array('slug'=>$sub['company']['slug']),'company') ?>"><?php echo $sub['company']['label'] ?></a>
		&gt; <a href="<?php echo $this->url(array('slug'=>$sub['company']['slug']),'company') ?>"><?php echo $sub['activity']['name'] ?></a>
		&gt; <a href="#"><?php echo $sub['label'] ?></a>
	</div>
	<div class="s-title"><strong><?php echo $sub['company']['name'] ?></strong></div>
	<div class="c-title"><strong><?php echo $sub['activity']['name']?></strong><em>成交额：<b><?php echo number_format($sub['amount'])?></b></em><em>成交率：<b><?php echo number_format($sub['deal_rate'], 2, '.', '')?>%</b></em></div>
	<div class="s-root">
		<a href="javascript:return(0)" class="switch">切换到大图</a>
	</div>
	<?php echo $this->partial('antique/rowset.phtml', array('antiques'=>$this->antiques)); ?>
</div>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', //Elastic/Jumping/All
                                    'pagination.phtml'); ?>
                                    
<script type="text/javascript">
$(document).ready(function(){
	// get last style of list
	setListStyle(getCookie('antiqueListStyle'));
	$('.switch').click(function(){
		if (getCookie('antiqueListStyle')=='pic') {
			setListStyle('list');
		} else {
			setListStyle('pic');
		}
	})
})

function setListStyle(style)
{
	if (style=='pic') {
		$('.column').hide();
		$('.s-pic em').show();
		$('.s-list').removeClass().addClass('s-pic');
		$('.s-pic em').show();
		setCookie('antiqueListStyle', 'pic');
		$('a.switch').text('切换到列表');
	} else {
		$('.column').show();
		$('.s-pic em').hide();
		$('.s-pic').removeClass().addClass('s-list');
		setCookie('antiqueListStyle', 'list');
		$('a.switch').text('切换到大图');
	}
}

function getCookie(c_name)
{
	if (document.cookie.length>0) {
  		c_start=document.cookie.indexOf(c_name + "=")
  		if (c_start!=-1) { 
    		c_start=c_start + c_name.length+1 
    		c_end=document.cookie.indexOf(";",c_start)
    		if (c_end==-1) c_end=document.cookie.length
    		return unescape(document.cookie.substring(c_start,c_end))
    	}
  	}
	return "";
}

function setCookie(c_name,value,expiredays)
{
	var exdate=new Date()
	exdate.setDate(exdate.getDate()+expiredays)
	document.cookie=c_name+ "=" +escape(value)+
	((expiredays==null) ? "" : ";expires="+exdate.toGMTString())
}

</script>
<?php echo $this->partial('footer.phtml'); ?>