<div class="footer">
	<a href="/site/contact">联系我们</a><em>|</em><a href="/site/about">关于我们</a><em>|</em><a href="/site/term">免责声明</a><em>|</em><a href="/site/friend-link">友情链接</a><br />
	<span>京ICP备09098036号</span><br />
	<span>版权所有&nbsp;&nbsp;2012paimaihui.net</span>
</div>
<!-- <script type="text/javascript" src="/js/jQuery.js"></script> -->
<!-- <script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>  -->
<script type="text/javascript">
function do_search(){
	if ($('#search_text').val()=='') {
		alert('请输入关键字');
	} else {
		keyword = $('#search_text').val();
		location.href = '<?php echo $this->url(array('controller'=>'antique', 'action'=>'list'), '', TRUE);?>/keyword/' + keyword;
	}
}
$('#search_button').click(function(){
	do_search();
});
$('#search_form').submit(function(){
	do_search();
	return false;
})


var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3Fd36a2511c28e8fe49634eec16630af94' type='text/javascript'%3E%3C/script%3E"));
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
  ga('create', 'UA-42859333-1', 'paimaihui.net');
  ga('send', 'pageview');
</script>
</body>
</html>
