<div class="footer">
	<a href="/site/contact/">商务合作</a><em>|</em><a href="/site/about/">关于我们</a><em>|</em><a href="/site/term/">免责声明</a><br />
	<span>京ICP备09098036号</span><br />
	<span>版权所有&nbsp;&nbsp;2012paimaihui.net</span>
</div>
<!-- <script type="text/javascript" src="/js/jQuery.js"></script> -->
<!-- <script type="text/javascript" src="/js/jquery.easing.1.3.js"></script>  -->
<script type="text/javascript">
function do_search(){
	if ($('#search_text').val()=='') {
		alert('请输入关键字');
	} else {
		keyword = $('#search_text').val();
		location.href = '<?php echo $this->url(array('controller'=>'antique', 'action'=>'list'), '', TRUE);?>/keyword/' + keyword;
	}
}
$('#search_button').click(function(){
	do_search();
});
$('#search_form').submit(function(){
	do_search();
	return false;
})
</script>
</body>
</html>