<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3c.org/TR/1999/REC-html401-19991224/loose.dtd">
<html>
<head>
    <title>拍卖会<?php if ($this->title) echo ' - '.$this->title; ?></title>
    <META http-equiv=content-type content="text/html; charset=UTF-8">
    <META http-equiv=Content-Style-Type content="text/css">
    <link rel="stylesheet" type="text/css" href="/css/listing.css">
    
    
</head>

<body>

    <div id="main" class="shadow-box">
        <div class="content"><span></span>
            <div id="header">
                <div id="logo"><a href="/"><img src="/images/logo.jpg" /></a></div>
                <div id="category">
                    <a href="#">全部</a>
                    <a href="<?php echo $this->url(array('action'=>'list','category'=>'瓷器')) ?>">瓷器</a>
                    <a href="<?php echo $this->url(array('action'=>'list','category'=>'书画')) ?>">书画</a>
                    <a href="<?php echo $this->url(array('action'=>'list','category'=>'油画')) ?>">油画</a>
                    <a href="<?php echo $this->url(array('action'=>'list','category'=>'邮品')) ?>">邮品</a>
                    <a href="<?php echo $this->url(array('action'=>'list','category'=>'钱币')) ?>">钱币</a>
                    <a href="#">更多...</a>
                </div>
                <div id="search">
                    <input id="search_text" type="text" name="search_text" />
                    <input id="search_button" type="image" src="/images/go.gif" />
                </div>
            </div>
