<!DOCTYPE html>
<html>
<head>
<title>拍卖会<?php if($this->title_ext) echo '__'.$this->title_ext; ?></title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="Keywords" content="拍卖会，春季拍卖会，秋季拍卖会，瓷器，古玩，古董，玉器，书画，邮品钱币，银锭，机制币，油画雕塑，乾隆，民国" /> 
<meta name="Description" content="拍卖会-中国领先的艺术品搜索引擎，所有网站数据及拍卖结果均由国内知名拍卖公司提供，并通过整合得到更优质结果，通过搜索找到相关结果。" />
<link rel="stylesheet" type="text/css" media="all" href="/css/auction.css" />
<link rel="stylesheet" type="text/css" media="all" href="/css/fixed.css" />
<link rel="shortcut icon" href='/images/favicon.png' />
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
</head>
<body>
<div class="header sum-head">
	<h1><a href="/" title="拍卖会"><img src="/images/logo.gif" alt="logo"/></a></h1>
	<form action="<?php echo $this->url(array('action'=>'list'), '', TRUE) ?>" method="get" class="search" id="search_form">
		<span>
			<input id="search_text" type="text" name="kw" value="<?php echo $this->keyword; ?>"/>
		</span>
		<input id="search_button" type="button" class="sea_sub" value=""/>
	</form>
</div>
