<?php if ($this->pageCount): ?>
<div id="pagination">
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">PRE/a> 
<?php else: ?>
  <a href="javascript:return(0)">PRE</a>
<?php endif; ?>
 
<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page)); ?>"><?php echo $page; ?></a> 
  <?php else: ?>
    <span class="selected"><?php echo $page; ?></span> 
  <?php endif; ?>
<?php endforeach; ?>
 
<!-- Next page link -->
<?php if (isset($this->next)): ?>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    NEXT
  </a>
<?php else: ?>
  <a href="javascript:return(0)">NEXT</a>
<?php endif; ?>
</div>
<?php endif; ?>