<!DOCTYPE html>
<html>
<head>
<title>拍卖会-中国领先的艺术品搜索引擎、2013年秋季拍卖会、拍卖直播、2012年秋季拍卖会、2013年春季拍卖会、北京诚轩拍卖公司、中国嘉德拍卖公司、北京保利拍卖公司、北京匡时拍卖公司</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="Keywords" content="拍卖会，春季拍卖会，秋季拍卖会，瓷器，古玩，古董，玉器，书画，邮品钱币，银锭，机制币，油画雕塑，乾隆，民国" /> 
<meta name="Description" content="拍卖会-中国领先的艺术品搜索引擎，所有网站数据及拍卖结果均由国内知名拍卖公司提供，并通过整合得到更优质结果，通过搜索找到相关结果。" />
<?php echo $this->headLink()->appendStylesheet('/css/auction.css') ?>
<?php echo $this->headLink()->appendStylesheet('/css/fixed.css') ?>
<?php echo $this->headLink(array('rel'=>'icon', 'href'=>'/images/favicon.png'), 'PREPEND'); ?>
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>

<script type="text/javascript">
$(document).ready(function(){
	$(window).scroll(function(){
		if($(this).scrollTop()>100){
			$('#toTop').fadeIn();
			if(!+[1,]){
				$("#toTop").css({top: $(window).scrollTop()+($(window).innerHeight() - 250)});
			};
		}else{
			$('#toTop').fadeOut();
		};
	});
	$('#toTop').click(function(){$('body,html').animate({scrollTop:0},300);});
});
</script>
</head>

<body>
<div class="header">
	<h1><a href="##" title="拍卖会"><img src="/images/logo.gif" alt="logo"/></a></h1>
	<div class="bread-crumb">
	<!-- 
		<a href="<?php echo $this->url(array('action'=>'list')) ?>" class="current">全部</a>
		<a href="##">瓷器</a>
		<a href="##">书画</a>
		<a href="##">油画</a>
		<a href="##">油品</a>
		<a href="##">钱币</a>
		<a href="##">更多...</a>
	 -->
	</div>
	<form class="search" id="search_form">
		<span>
			<input type="text" name="kw" id="search_text" />
		</span>
		<input type="button" class="sea_sub" id="search_button" value=""/>
	</form>
	<p class="msg">
		<!-- 北京诚轩2012年秋季拍卖会现在开始征集拍品<br />日期：2012年10月22日<br />地点：北京昆仑饭店 -->
	</p>
</div>
<div class="conter home-con">
	<!-- <h2>精品展示</h2> -->
	<ul class="clearfix">
	<?php 
	$subs = $this->subs;
	foreach ($subs as $sub): ?>
		<li>
			<a href="<?php echo $this->url(array('controller'=>'sub-activity', action=>'show', 'id'=>$sub['sub_id']));?>"  class="p" ><b style="background-image:url(<?php echo $sub['image'] ?>)"></b></a>
			<a href="<?php echo $this->url(array('controller'=>'sub-activity', action=>'show', 'id'=>$sub['sub_id']));?>"><?php echo $sub['name']?></a>
		</li>
	<?php endforeach;?>
	</ul>
	<!-- 
	<div class="pager">
		<em>首页</em>
		<span>上一页</span>
		<a href="" class="current">1</a>
		<a href="">2</a>
		<a href="">3</a>
		<a href="">4</a>
		<a href="">5</a>
		<span>下一页</span>
		<em>尾页</em>
	</div>
	 -->
	<div class=""><a href="<?php echo $this->url(array('slug'=>'guardian'), 'company');?>"><img src="/images/logo-1.jpg" 
	/></a><a href="<?php echo $this->url(array('slug'=>'poly'), 'company');?>"><img src="/images/logo-2.jpg" 
	/></a><a href="<?php echo $this->url(array('slug'=>'chengxuan'), 'company');?>"><img src="/images/logo-3.jpg" 
	/></a><a href="<?php echo $this->url(array('slug'=>'council'), 'company');?>"><img src="/images/logo-4.jpg" /
	></a>
	</div>
</div>
<div id="toTop"></div>
<div id="leftBanner" style="width:120px;
text-align:center;
position:fixed;
*position:absolute;
top:200px;
left:20px;
"><a href="http://live.chengxuan.com" target="_blank"><img src="images/chengxuan_banner.jpg" /></a></div>
<?php echo $this->partial('footer.phtml'); ?>
