<!DOCTYPE html>
<html>
<head>
<title>拍卖会 </title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="Keywords" content="" /> 
<?php echo $this->headLink()->appendStylesheet('/css/auction.css') ?>
<script src="http://lib.sinaapp.com/js/jquery/1.7.2/jquery.min.js"></script>
</head>

<body>
<div class="header">
	<h1><a href="##" title="拍卖会"><img src="/images/logo.gif" alt="logo"/></a></h1>
	<div class="bread-crumb">
	<!-- 
		<a href="<?php echo $this->url(array('action'=>'list')) ?>" class="current">全部</a>
		<a href="##">瓷器</a>
		<a href="##">书画</a>
		<a href="##">油画</a>
		<a href="##">油品</a>
		<a href="##">钱币</a>
		<a href="##">更多...</a>
	 -->
	</div>
	<form class="search" id="search_form">
		<span>
			<input type="text" name="kw" id="search_text" />
		</span>
		<input type="button" class="sea_sub" id="search_button" value=""/>
	</form>
	<p class="msg">
		<!-- 北京诚轩2012年秋季拍卖会现在开始征集拍品<br />日期：2012年10月22日<br />地点：北京昆仑饭店 -->
	</p>
</div>
<div class="conter home-con">
	<h2><!-- 精品展示 --></h2>
	<ul class="clearfix">
	<?php 
	$subs = $this->subActivity;
	foreach ($subs as $sub): ?>
		<li>
			<img src="/images/picture-1.jpg" alt="商品展示图"/>
			<a href="<?php echo $this->url(array('controller'=>'sub-activity', action=>'show', 'id'=>$sub['id']));?>"><?php echo $sub['name']?></a>
		</li>
	<?php endforeach;?>
	</ul>
	<!-- 
	<div class="pager">
		<em>首页</em>
		<span>上一页</span>
		<a href="" class="current">1</a>
		<a href="">2</a>
		<a href="">3</a>
		<a href="">4</a>
		<a href="">5</a>
		<span>下一页</span>
		<em>尾页</em>
	</div>
	 -->
	<div class="partner">
		<a href=""><img src="/images/logo-1.gif"></a>
		<a href=""><img src="/images/logo-2.gif"></a>
		<a href=""><img src="/images/logo-3.gif"></a>
		<a href="<?php echo $this->url(array('slug'=>'guardian'), 'company');?>"><img src="/images/logo-4.gif"></a>
		<a href=""><img src="/images/logo-5.gif"></a>
		<a href=""><img src="/images/logo-6.gif"></a>
	</div>
</div>

<?php echo $this->partial('footer.phtml'); ?>