<?php echo $this->partial('header.phtml', array('title_ext'=>$this->keyword, 'keyword'=>$this->keyword)); ?>

<div class="conter s-con">
	<div class="subnav">当前位置：<a href="/">首页</a> &gt; 拍品搜索</div>
	<div class="s-root">
		<a href="javascript:return(0)" class="switch">切换到大图</a>
		<!--
		<span>估价<i class="top">▲</i></span> 
		<span><a href="<?php echo $this->url(array('sort'=>'priceup', 'page'=>1))?>">成交价</a><i class="bottom">▼</i></span>
		<span>日期<i class="top"></i></span>
		 -->
	</div>
	<!--大图展现 ul用s-pic 类名    列表形式用s-list -->
	<?php echo $this->partial('antique/rowset.phtml', array('antiques'=>$this->antiques)); ?>
</div>

<?php echo $this->paginationControl($this->paginator,
                                    'Sliding', //Elastic/Jumping/All
                                    'pagination.phtml'); ?>

<!-- <div id="counting">共<?php echo number_format($this->total) ?>条结果</div> -->

<script type="text/javascript">
$(document).ready(function(){
	// get last style of list
	setListStyle(getCookie('antiqueListStyle'));
	$('.switch').click(function(){
		if (getCookie('antiqueListStyle')=='pic') {
			setListStyle('list');
		} else {
			setListStyle('pic');
		}
	})
})

function setListStyle(style)
{
	if (style=='pic') {
		$('.column').hide();
		$('.s-pic em').show();
		$('.s-list').removeClass().addClass('s-pic');
		$('.s-pic em').show();
		setCookie('antiqueListStyle', 'pic');
		$('a.switch').text('切换到列表');
	} else {
		$('.column').show();
		$('.s-pic em').hide();
		$('.s-pic').removeClass().addClass('s-list');
		setCookie('antiqueListStyle', 'list');
		$('a.switch').text('切换到大图');
	}
}

function getCookie(c_name)
{
	if (document.cookie.length>0) {
  		c_start=document.cookie.indexOf(c_name + "=")
  		if (c_start!=-1) { 
    		c_start=c_start + c_name.length+1 
    		c_end=document.cookie.indexOf(";",c_start)
    		if (c_end==-1) c_end=document.cookie.length
    		return unescape(document.cookie.substring(c_start,c_end))
    	}
  	}
	return "";
}

function setCookie(c_name,value,expiredays)
{
	var exdate=new Date()
	exdate.setDate(exdate.getDate()+expiredays)
	document.cookie=c_name+ "=" +escape(value)+
	((expiredays==null) ? "" : ";expires="+exdate.toGMTString())
}

</script>
<?php echo $this->partial('footer.phtml'); ?>