<?php echo $this->partial('header.phtml', array('title'=>$this->title)); ?>
<?php $antique = $this->antique;
?>
<div class="conter d-con">
	<div class="subnav">当前位置：<a href="##">首页</a>&gt;<span>拍卖品详情</span></div>
	<h2>拍卖品详情</h2>
	<div class="exhibition">
		<strong><?php echo $antique['name'] ?></strong>
	<?php foreach ($antique['photo'] as $k=>$v): ?>
		<div class="d-img">
			<a class="big" href="<?php echo $v['url']?>" target="_blank"></a><img src="<?php echo $v['url_thumb_345'] ?>" alt="logo"/>
		</div>
	<?php endforeach;?>
		<em>图片仅供参考</em>
	</div>
	<div class="d-inf clearfix">
		<span>LOT号：<?php echo $antique['lot'] ?><br />公司名称：<?php echo $antique['company']['name'] ?></span>
		<span>尺寸：<?php echo $antique['size'] ?><br />拍卖会：<?php echo $antique['activity']['name'] ?></span>
		<span>年代：<?php echo $antique['period'] ?><br />专场：<?php echo $antique['sub_activity']['name'] ?></span>
		<span>估价：<?php echo $antique['estimate'] ?><br /> 成交价：<?php echo $antique['price'] ?><br />拍卖日期：2012.04.05</span>
	</div>
	<div class="d-inf">
		<?php echo $antique['description'] ?>
	</div>
	<p class="d-inf">声明：本拍品信息来源于拍卖机构，本网不对拍卖品真伪及价格负责</p>
</div>

<!-- 
<div class="conter scrool">
	<h5>相关拍品</h5>
	<a href="##" class="left">&lt;</a><a href="##" class="right">&gt;</a>
	<div>
		<ul>
			<li>
				<a href="##"><img src="images/picture-1.jpg" alt="logo"/></a>
				<a href="##">汝窑精品粉底富贵瓶</a>
			</li>
		</ul>
	</div>
</div>
-->
<!-- 
<script src="/js/fancybox/jquery.fancybox-1.3.4.pack.js"></script>
<link rel="stylesheet" href="/js/fancybox/jquery.fancybox-1.3.4.css" type="text/css" media="screen" />
<script type="text/javascript">
$(document).ready(function() {
	$("a.ddd").fancybox({
		'transitionIn'	:	'elastic',
		'transitionOut'	:	'elastic',
		'speedIn'		:	600, 
		'speedOut'		:	200, 
		'overlayShow'	:	false
	});
});
</script>
 -->
<?php echo $this->partial('footer.phtml'); ?>